// Starter company lists people can add during setup or from Scout.
// These are only suggestions: each company gets a careers-search link and can be removed.
// `tags` are matched against the person's titles and strengths to put the most relevant lists first.
// Notes stay short and factual (HQ or what the company is known for), so they don't go stale.

export const PACK_CATEGORIES = ['Tech', 'Money', 'Health', 'Consumer', 'Industrial & energy', 'Services & mission', 'Work style'];

export const COMPANY_PACKS = [
  // ---------- Tech ----------
  {
    id: 'big-tech',
    label: 'Big Tech',
    category: 'Tech',
    tags: ['software', 'engineer', 'product', 'data', 'design', 'tech'],
    companies: [
      { name: 'Apple', note: 'Cupertino, CA' },
      { name: 'Microsoft', note: 'Redmond, WA' },
      { name: 'Google', note: 'Mountain View, CA' },
      { name: 'Amazon', note: 'Seattle, WA' },
      { name: 'Meta', note: 'Menlo Park, CA' },
      { name: 'NVIDIA', note: 'Santa Clara, CA' },
      { name: 'Salesforce', note: 'San Francisco, CA' },
      { name: 'Netflix', note: 'Los Gatos, CA' },
    ],
  },
  {
    id: 'saas',
    label: 'SaaS & cloud software',
    category: 'Tech',
    tags: ['saas', 'software', 'customer success', 'product marketing', 'demand gen', 'account executive', 'b2b'],
    companies: [
      { name: 'HubSpot', note: 'Boston, MA. Marketing and sales software.' },
      { name: 'ServiceNow', note: 'Santa Clara, CA' },
      { name: 'Workday', note: 'Pleasanton, CA' },
      { name: 'Adobe', note: 'San Jose, CA' },
      { name: 'Atlassian', note: 'Jira, Confluence. Remote-friendly.' },
      { name: 'Intuit', note: 'Mountain View, CA. TurboTax, QuickBooks.' },
      { name: 'Datadog', note: 'New York, NY' },
      { name: 'Twilio', note: 'San Francisco, CA' },
      { name: 'Zoom', note: 'San Jose, CA' },
    ],
  },
  {
    id: 'ai',
    label: 'AI companies',
    category: 'Tech',
    tags: ['ai', 'machine learning', 'ml', 'data', 'research', 'engineer'],
    companies: [
      { name: 'OpenAI', note: 'San Francisco, CA' },
      { name: 'Anthropic', note: 'San Francisco, CA' },
      { name: 'Databricks', note: 'San Francisco, CA' },
      { name: 'Scale AI', note: 'San Francisco, CA' },
      { name: 'Hugging Face', note: 'New York and Paris' },
      { name: 'Cohere', note: 'Toronto, ON' },
    ],
  },
  {
    id: 'cyber',
    label: 'Cybersecurity',
    category: 'Tech',
    tags: ['security', 'cyber', 'infosec', 'it'],
    companies: [
      { name: 'CrowdStrike', note: 'Austin, TX' },
      { name: 'Palo Alto Networks', note: 'Santa Clara, CA' },
      { name: 'Cloudflare', note: 'San Francisco, CA' },
      { name: 'Okta', note: 'San Francisco, CA' },
      { name: 'Zscaler', note: 'San Jose, CA' },
      { name: 'Fortinet', note: 'Sunnyvale, CA. Big channel partner program.' },
    ],
  },
  {
    id: 'tech-partners',
    label: 'Tech hardware & partner programs',
    category: 'Tech',
    tags: ['channel', 'partner', 'reseller', 'mdf', 'distributor', 'hardware', 'enablement', 'alliances'],
    companies: [
      { name: 'Dell Technologies', note: 'Round Rock, TX. Large partner program.' },
      { name: 'Lenovo', note: 'North America HQ in Morrisville, NC.' },
      { name: 'HP Inc.', note: 'Palo Alto, CA. Partner-first go-to-market.' },
      { name: 'Cisco', note: 'San Jose, CA. One of the biggest partner ecosystems.' },
      { name: 'Intel', note: 'Santa Clara, CA' },
      { name: 'Logitech', note: 'Retail and B2B channel.' },
    ],
  },
  {
    id: 'gaming',
    label: 'Gaming',
    category: 'Tech',
    tags: ['gaming', 'games', 'community', 'esports', 'live stream', 'creator'],
    companies: [
      { name: 'Electronic Arts', note: 'Redwood City, CA' },
      { name: 'Epic Games', note: 'Cary, NC' },
      { name: 'Riot Games', note: 'Los Angeles, CA' },
      { name: 'Nintendo of America', note: 'Redmond, WA' },
      { name: 'Roblox', note: 'San Mateo, CA' },
      { name: 'Take-Two Interactive', note: 'New York, NY. Rockstar, 2K.' },
    ],
  },
  {
    id: 'media',
    label: 'Media & entertainment',
    category: 'Tech',
    tags: ['media', 'content', 'social media', 'video', 'brand', 'creative', 'entertainment', 'pr'],
    companies: [
      { name: 'The Walt Disney Company', note: 'Burbank, CA' },
      { name: 'Warner Bros. Discovery', note: 'New York, NY' },
      { name: 'Spotify', note: 'Stockholm and New York' },
      { name: 'Paramount', note: 'New York, NY' },
      { name: 'iHeartMedia', note: 'San Antonio, TX' },
      { name: 'The New York Times', note: 'New York, NY' },
    ],
  },
  {
    id: 'telecom',
    label: 'Telecom',
    category: 'Tech',
    tags: ['telecom', 'wireless', 'retail', 'channel', 'dealer'],
    companies: [
      { name: 'Verizon', note: 'New York, NY' },
      { name: 'AT&T', note: 'Dallas, TX' },
      { name: 'T-Mobile', note: 'Bellevue, WA' },
      { name: 'Comcast', note: 'Philadelphia, PA' },
      { name: 'Charter Communications', note: 'Stamford, CT. Spectrum.' },
    ],
  },

  // ---------- Money ----------
  {
    id: 'fintech',
    label: 'Fintech & payments',
    category: 'Money',
    tags: ['fintech', 'payments', 'finance', 'crypto', 'growth'],
    companies: [
      { name: 'Stripe', note: 'San Francisco and Dublin' },
      { name: 'PayPal', note: 'San Jose, CA' },
      { name: 'Block', note: 'Oakland, CA. Square, Cash App.' },
      { name: 'Visa', note: 'San Francisco, CA' },
      { name: 'Mastercard', note: 'Purchase, NY' },
      { name: 'Plaid', note: 'San Francisco, CA' },
      { name: 'Chime', note: 'San Francisco, CA' },
      { name: 'Robinhood', note: 'Menlo Park, CA' },
    ],
  },
  {
    id: 'banking',
    label: 'Banking & investing',
    category: 'Money',
    tags: ['bank', 'finance', 'financial', 'wealth', 'analyst', 'accounting'],
    companies: [
      { name: 'JPMorgan Chase', note: 'New York, NY' },
      { name: 'Bank of America', note: 'Charlotte, NC' },
      { name: 'Wells Fargo', note: 'San Francisco, CA' },
      { name: 'Capital One', note: 'McLean, VA' },
      { name: 'Truist', note: 'Charlotte, NC' },
      { name: 'Fidelity Investments', note: 'Boston, MA' },
      { name: 'Charles Schwab', note: 'Westlake, TX' },
      { name: 'American Express', note: 'New York, NY' },
    ],
  },
  {
    id: 'insurance',
    label: 'Insurance',
    category: 'Money',
    tags: ['insurance', 'claims', 'underwriting', 'agent', 'risk'],
    companies: [
      { name: 'State Farm', note: 'Bloomington, IL. Agent channel.' },
      { name: 'Progressive', note: 'Mayfield Village, OH' },
      { name: 'Allstate', note: 'Northbrook, IL' },
      { name: 'USAA', note: 'San Antonio, TX' },
      { name: 'Liberty Mutual', note: 'Boston, MA' },
      { name: 'Lemonade', note: 'New York, NY' },
    ],
  },
  {
    id: 'real-estate',
    label: 'Real estate & proptech',
    category: 'Money',
    tags: ['real estate', 'property', 'leasing', 'broker', 'construction'],
    companies: [
      { name: 'Zillow', note: 'Seattle, WA' },
      { name: 'CBRE', note: 'Dallas, TX' },
      { name: 'JLL', note: 'Chicago, IL' },
      { name: 'Redfin', note: 'Seattle, WA' },
      { name: 'Compass', note: 'New York, NY' },
    ],
  },

  // ---------- Health ----------
  {
    id: 'healthcare',
    label: 'Health systems & insurers',
    category: 'Health',
    tags: ['health', 'healthcare', 'hospital', 'clinical', 'patient', 'nurse'],
    companies: [
      { name: 'UnitedHealth Group', note: 'Minnetonka, MN' },
      { name: 'CVS Health', note: 'Woonsocket, RI' },
      { name: 'Kaiser Permanente', note: 'Oakland, CA' },
      { name: 'HCA Healthcare', note: 'Nashville, TN' },
      { name: 'Elevance Health', note: 'Indianapolis, IN' },
      { name: 'Cigna Group', note: 'Bloomfield, CT' },
      { name: 'Mayo Clinic', note: 'Rochester, MN' },
    ],
  },
  {
    id: 'pharma',
    label: 'Pharma & biotech',
    category: 'Health',
    tags: ['pharma', 'biotech', 'clinical', 'medical', 'science', 'lab'],
    companies: [
      { name: 'Eli Lilly', note: 'Indianapolis, IN' },
      { name: 'Pfizer', note: 'New York, NY' },
      { name: 'Johnson & Johnson', note: 'New Brunswick, NJ' },
      { name: 'Merck', note: 'Rahway, NJ' },
      { name: 'AbbVie', note: 'North Chicago, IL' },
      { name: 'Amgen', note: 'Thousand Oaks, CA' },
      { name: 'Genentech', note: 'South San Francisco, CA' },
      { name: 'Moderna', note: 'Cambridge, MA' },
    ],
  },
  {
    id: 'medtech',
    label: 'Medical devices',
    category: 'Health',
    tags: ['medical device', 'medtech', 'clinical', 'sales', 'surgical', 'distributor'],
    companies: [
      { name: 'Medtronic', note: 'US operations in Minneapolis, MN.' },
      { name: 'Stryker', note: 'Kalamazoo, MI' },
      { name: 'Boston Scientific', note: 'Marlborough, MA' },
      { name: 'Abbott', note: 'Abbott Park, IL' },
      { name: 'Intuitive Surgical', note: 'Sunnyvale, CA' },
      { name: 'BD (Becton Dickinson)', note: 'Franklin Lakes, NJ' },
      { name: 'Zimmer Biomet', note: 'Warsaw, IN' },
    ],
  },

  // ---------- Consumer ----------
  {
    id: 'cpg',
    label: 'Consumer packaged goods',
    category: 'Consumer',
    tags: ['brand', 'brand manager', 'cpg', 'shopper', 'trade marketing', 'retail', 'category'],
    companies: [
      { name: 'Procter & Gamble', note: 'Cincinnati, OH. The classic brand-management school.' },
      { name: 'PepsiCo', note: 'Purchase, NY' },
      { name: 'The Coca-Cola Company', note: 'Atlanta, GA' },
      { name: 'Unilever', note: 'US HQ in Englewood Cliffs, NJ.' },
      { name: 'General Mills', note: 'Minneapolis, MN' },
      { name: 'Kraft Heinz', note: 'Chicago and Pittsburgh' },
      { name: 'Colgate-Palmolive', note: 'New York, NY' },
      { name: 'Clorox', note: 'Oakland, CA' },
      { name: 'Kimberly-Clark', note: 'Dallas area, TX' },
    ],
  },
  {
    id: 'food-bev',
    label: 'Food & beverage',
    category: 'Consumer',
    tags: ['food', 'beverage', 'brand', 'trade marketing', 'shopper', 'category', 'distributor'],
    companies: [
      { name: 'Mars', note: 'McLean, VA. Snacks, pet care, food.' },
      { name: 'The Hershey Company', note: 'Hershey, PA' },
      { name: 'Keurig Dr Pepper', note: 'Burlington, MA and Frisco, TX' },
      { name: 'Nestlé USA', note: 'Arlington, VA' },
      { name: 'Constellation Brands', note: 'Rochester, NY. Modelo, Corona in the US.' },
      { name: 'Molson Coors', note: 'Chicago and Golden, CO' },
      { name: 'Danone North America', note: 'Yogurt, plant-based, waters.' },
    ],
  },
  {
    id: 'retail',
    label: 'Retail & e-commerce',
    category: 'Consumer',
    tags: ['retail', 'e-commerce', 'ecommerce', 'merchandising', 'buyer', 'store', 'shopper'],
    companies: [
      { name: 'Walmart', note: 'Bentonville, AR' },
      { name: 'Target', note: 'Minneapolis, MN' },
      { name: 'The Home Depot', note: 'Atlanta, GA' },
      { name: 'Lowe’s', note: 'Mooresville, NC' },
      { name: 'Costco', note: 'Issaquah, WA' },
      { name: 'Best Buy', note: 'Richfield, MN' },
      { name: 'Wayfair', note: 'Boston, MA' },
      { name: 'Etsy', note: 'Brooklyn, NY' },
    ],
  },
  {
    id: 'apparel',
    label: 'Apparel & footwear',
    category: 'Consumer',
    tags: ['apparel', 'fashion', 'footwear', 'brand', 'merchandising', 'design', 'wholesale'],
    companies: [
      { name: 'Nike', note: 'Beaverton, OR' },
      { name: 'adidas', note: 'North America HQ in Portland, OR.' },
      { name: 'lululemon', note: 'Vancouver, BC' },
      { name: 'Levi Strauss & Co.', note: 'San Francisco, CA' },
      { name: 'VF Corporation', note: 'The North Face, Vans, Timberland.' },
      { name: 'Columbia Sportswear', note: 'Portland, OR' },
      { name: 'Hanesbrands', note: 'Winston-Salem, NC' },
      { name: 'Under Armour', note: 'Baltimore, MD' },
    ],
  },
  {
    id: 'beauty',
    label: 'Beauty & personal care',
    category: 'Consumer',
    tags: ['beauty', 'cosmetics', 'skincare', 'brand', 'influencer', 'social media'],
    companies: [
      { name: 'The Estée Lauder Companies', note: 'New York, NY' },
      { name: 'L’Oréal USA', note: 'New York, NY' },
      { name: 'Ulta Beauty', note: 'Bolingbrook, IL' },
      { name: 'Sephora', note: 'US HQ in San Francisco, CA.' },
      { name: 'e.l.f. Beauty', note: 'Oakland, CA' },
      { name: 'Coty', note: 'New York, NY' },
    ],
  },
  {
    id: 'sports',
    label: 'Sports, fitness & outdoors',
    category: 'Consumer',
    tags: ['sports', 'fitness', 'outdoor', 'collectibles', 'cards', 'live stream', 'brand', 'dealer'],
    companies: [
      { name: 'YETI', note: 'Austin, TX' },
      { name: 'Garmin', note: 'Olathe, KS' },
      { name: 'REI', note: 'Kent, WA. Co-op.' },
      { name: 'Patagonia', note: 'Ventura, CA' },
      { name: 'Dick’s Sporting Goods', note: 'Pittsburgh area, PA' },
      { name: 'Peloton', note: 'New York, NY' },
      { name: 'Fanatics (Topps)', note: 'Licensing, e-commerce, trading cards.' },
      { name: 'Panini America', note: 'Trading cards and the hobby-shop channel.' },
    ],
  },
  {
    id: 'home',
    label: 'Home, kitchen & outdoor living',
    category: 'Consumer',
    tags: ['home', 'appliance', 'furniture', 'kitchen', 'retail', 'dealer', 'brand'],
    companies: [
      { name: 'Whirlpool', note: 'Benton Harbor, MI' },
      { name: 'Williams-Sonoma', note: 'San Francisco, CA. Pottery Barn, West Elm.' },
      { name: 'IKEA US', note: 'Conshohocken, PA' },
      { name: 'Weber', note: 'Palatine, IL. Grills.' },
      { name: 'Traeger', note: 'Salt Lake City, UT. Dealer and retail channel.' },
      { name: 'SharkNinja', note: 'Needham, MA' },
    ],
  },
  {
    id: 'pet',
    label: 'Pet',
    category: 'Consumer',
    tags: ['pet', 'veterinary', 'brand', 'retail', 'e-commerce'],
    companies: [
      { name: 'Chewy', note: 'Dania Beach, FL' },
      { name: 'Petco', note: 'San Diego, CA' },
      { name: 'PetSmart', note: 'Phoenix, AZ' },
      { name: 'Mars Petcare', note: 'Pedigree, Royal Canin, VCA.' },
      { name: 'Hill’s Pet Nutrition', note: 'Topeka, KS' },
    ],
  },
  {
    id: 'hospitality',
    label: 'Restaurants & hospitality',
    category: 'Consumer',
    tags: ['hospitality', 'restaurant', 'hotel', 'franchise', 'guest', 'operations'],
    companies: [
      { name: 'Marriott International', note: 'Bethesda, MD' },
      { name: 'Hilton', note: 'McLean, VA' },
      { name: 'Hyatt', note: 'Chicago, IL' },
      { name: 'Starbucks', note: 'Seattle, WA' },
      { name: 'McDonald’s', note: 'Chicago, IL' },
      { name: 'Chick-fil-A', note: 'Atlanta, GA' },
      { name: 'Chipotle', note: 'Newport Beach, CA' },
      { name: 'Darden Restaurants', note: 'Orlando, FL. Olive Garden, LongHorn.' },
    ],
  },
  {
    id: 'travel',
    label: 'Travel & airlines',
    category: 'Consumer',
    tags: ['travel', 'airline', 'loyalty', 'hospitality', 'customer experience'],
    companies: [
      { name: 'Delta Air Lines', note: 'Atlanta, GA' },
      { name: 'United Airlines', note: 'Chicago, IL' },
      { name: 'Southwest Airlines', note: 'Dallas, TX' },
      { name: 'American Airlines', note: 'Fort Worth, TX' },
      { name: 'Airbnb', note: 'San Francisco, CA' },
      { name: 'Expedia Group', note: 'Seattle, WA' },
      { name: 'Booking Holdings', note: 'Norwalk, CT. Booking.com, Priceline.' },
    ],
  },

  // ---------- Industrial & energy ----------
  {
    id: 'tools',
    label: 'Tools & hardware',
    category: 'Industrial & energy',
    tags: ['tools', 'hardware', 'channel', 'trade', 'dealer', 'distributor', 'mdf', 'co-op', 'trade show', 'home depot', 'lowe'],
    companies: [
      { name: 'Techtronic Industries (TTI)', note: 'Milwaukee, Ryobi. North America HQ in Anderson, SC.' },
      { name: 'Milwaukee Tool', note: 'Brookfield, WI. Heavy trade and channel marketing.' },
      { name: 'Stanley Black & Decker', note: 'DeWalt, Craftsman. Big retail and channel teams.' },
      { name: 'Bosch', note: 'Power tools and a large US manufacturing footprint.' },
      { name: 'Snap-on', note: 'Kenosha, WI. Franchise and dealer channel.' },
      { name: 'Klein Tools', note: 'Distributor-driven, family-owned.' },
      { name: 'Husqvarna', note: 'Dealer network. North America HQ in Charlotte.' },
      { name: 'Makita USA', note: 'La Mirada, CA' },
    ],
  },
  {
    id: 'building',
    label: 'Building products',
    category: 'Industrial & energy',
    tags: ['building', 'construction', 'contractor', 'pro', 'dealer', 'distributor', 'home improvement', 'channel'],
    companies: [
      { name: 'Sherwin-Williams', note: 'Cleveland, OH' },
      { name: 'Owens Corning', note: 'Toledo, OH' },
      { name: 'Masco', note: 'Livonia, MI. Delta Faucet, Behr.' },
      { name: 'Carrier', note: 'Palm Beach Gardens, FL. HVAC dealer channel.' },
      { name: 'Trane Technologies', note: 'HVAC. US operations in Davidson, NC.' },
      { name: 'Mohawk Industries', note: 'Calhoun, GA. Flooring.' },
      { name: 'Andersen Windows & Doors', note: 'Bayport, MN' },
    ],
  },
  {
    id: 'industrial',
    label: 'Industrial manufacturing',
    category: 'Industrial & energy',
    tags: ['manufacturing', 'industrial', 'engineering', 'operations', 'supply chain', 'distributor', 'channel'],
    companies: [
      { name: '3M', note: 'St. Paul, MN' },
      { name: 'Honeywell', note: 'Charlotte, NC' },
      { name: 'Caterpillar', note: 'Irving, TX. Dealer network.' },
      { name: 'John Deere', note: 'Moline, IL. Dealer network.' },
      { name: 'Emerson', note: 'St. Louis, MO' },
      { name: 'Parker Hannifin', note: 'Cleveland, OH. Distributor channel.' },
      { name: 'Eaton', note: 'US operations in Cleveland, OH.' },
      { name: 'Milliken & Company', note: 'Spartanburg, SC' },
    ],
  },
  {
    id: 'distribution',
    label: 'Distributors',
    category: 'Industrial & energy',
    tags: ['distributor', 'distribution', 'channel', 'vendor', 'supplier', 'b2b', 'sales', 'mdf'],
    companies: [
      { name: 'Grainger', note: 'Lake Forest, IL. Industrial supply.' },
      { name: 'Fastenal', note: 'Winona, MN' },
      { name: 'Ferguson', note: 'Newport News, VA. Plumbing and HVAC.' },
      { name: 'CDW', note: 'Vernon Hills, IL. IT solutions.' },
      { name: 'Ingram Micro', note: 'Irvine, CA. IT distribution.' },
      { name: 'Arrow Electronics', note: 'Centennial, CO' },
      { name: 'Sysco', note: 'Houston, TX. Foodservice.' },
    ],
  },
  {
    id: 'auto',
    label: 'Automotive & EV',
    category: 'Industrial & energy',
    tags: ['automotive', 'auto', 'ev', 'dealer', 'mobility', 'tires', 'aftermarket'],
    companies: [
      { name: 'Ford', note: 'Dearborn, MI' },
      { name: 'General Motors', note: 'Detroit, MI' },
      { name: 'Tesla', note: 'Austin, TX' },
      { name: 'Toyota North America', note: 'Plano, TX' },
      { name: 'Rivian', note: 'Irvine, CA' },
      { name: 'BMW Manufacturing', note: 'Greer, SC' },
      { name: 'Michelin North America', note: 'Greenville, SC. Dealer and fleet channels.' },
      { name: 'Bridgestone Americas', note: 'Nashville, TN' },
    ],
  },
  {
    id: 'aerospace',
    label: 'Aerospace & defense',
    category: 'Industrial & energy',
    tags: ['aerospace', 'defense', 'engineering', 'program manager', 'government', 'clearance'],
    companies: [
      { name: 'Lockheed Martin', note: 'Bethesda, MD' },
      { name: 'Boeing', note: 'Arlington, VA' },
      { name: 'RTX', note: 'Arlington, VA. Pratt & Whitney, Collins, Raytheon.' },
      { name: 'Northrop Grumman', note: 'Falls Church, VA' },
      { name: 'General Dynamics', note: 'Reston, VA' },
      { name: 'SpaceX', note: 'Launch and Starlink.' },
    ],
  },
  {
    id: 'energy',
    label: 'Energy & utilities',
    category: 'Industrial & energy',
    tags: ['energy', 'utility', 'oil', 'gas', 'power', 'grid'],
    companies: [
      { name: 'NextEra Energy', note: 'Juno Beach, FL' },
      { name: 'Duke Energy', note: 'Charlotte, NC' },
      { name: 'Southern Company', note: 'Atlanta, GA' },
      { name: 'GE Vernova', note: 'Power and wind. Large Greenville, SC presence.' },
      { name: 'ExxonMobil', note: 'Houston area, TX' },
      { name: 'Chevron', note: 'Houston, TX' },
    ],
  },
  {
    id: 'climate',
    label: 'Climate & clean energy',
    category: 'Industrial & energy',
    tags: ['climate', 'solar', 'clean energy', 'sustainability', 'ev', 'battery'],
    companies: [
      { name: 'First Solar', note: 'Tempe, AZ' },
      { name: 'Enphase Energy', note: 'Fremont, CA. Installer channel.' },
      { name: 'Sunrun', note: 'San Francisco, CA' },
      { name: 'Tesla Energy', note: 'Powerwall and solar.' },
      { name: 'Rivian', note: 'Irvine, CA' },
    ],
  },
  {
    id: 'logistics',
    label: 'Logistics & supply chain',
    category: 'Industrial & energy',
    tags: ['logistics', 'supply chain', 'operations', 'freight', 'warehouse', 'transportation'],
    companies: [
      { name: 'UPS', note: 'Atlanta, GA' },
      { name: 'FedEx', note: 'Memphis, TN' },
      { name: 'C.H. Robinson', note: 'Eden Prairie, MN' },
      { name: 'J.B. Hunt', note: 'Lowell, AR' },
      { name: 'Flexport', note: 'San Francisco, CA' },
      { name: 'Ryder', note: 'Miami, FL' },
    ],
  },

  // ---------- Services & mission ----------
  {
    id: 'consulting',
    label: 'Consulting & professional services',
    category: 'Services & mission',
    tags: ['consulting', 'consultant', 'strategy', 'advisory', 'audit', 'accounting'],
    companies: [
      { name: 'Deloitte', note: 'Consulting, audit, tax.' },
      { name: 'Accenture', note: 'Consulting and technology services.' },
      { name: 'McKinsey & Company', note: 'Strategy consulting.' },
      { name: 'Boston Consulting Group', note: 'Strategy consulting.' },
      { name: 'Bain & Company', note: 'Strategy consulting.' },
      { name: 'PwC', note: 'Audit, tax, consulting.' },
      { name: 'EY', note: 'Audit, tax, consulting.' },
    ],
  },
  {
    id: 'education',
    label: 'Education & edtech',
    category: 'Services & mission',
    tags: ['education', 'edtech', 'learning', 'teacher', 'training', 'curriculum', 'instructional'],
    companies: [
      { name: 'Duolingo', note: 'Pittsburgh, PA' },
      { name: 'Coursera', note: 'Mountain View, CA' },
      { name: 'Instructure', note: 'Salt Lake City, UT. Canvas.' },
      { name: 'Pearson', note: 'Learning materials and assessments.' },
      { name: 'Khan Academy', note: 'Nonprofit. Mountain View, CA.' },
    ],
  },
  {
    id: 'nonprofit',
    label: 'Nonprofits & foundations',
    category: 'Services & mission',
    tags: ['nonprofit', 'fundraising', 'development', 'mission', 'community', 'grants'],
    companies: [
      { name: 'Gates Foundation', note: 'Seattle, WA' },
      { name: 'American Red Cross', note: 'Washington, DC' },
      { name: 'St. Jude Children’s Research Hospital', note: 'Memphis, TN' },
      { name: 'Habitat for Humanity', note: 'Atlanta, GA' },
      { name: 'Feeding America', note: 'Chicago, IL' },
      { name: 'World Wildlife Fund', note: 'Washington, DC' },
    ],
  },

  // ---------- Work style ----------
  {
    id: 'remote',
    label: 'Remote-first companies',
    category: 'Work style',
    tags: ['remote'],
    companies: [
      { name: 'GitLab', note: 'All-remote.' },
      { name: 'Automattic', note: 'WordPress.com, Tumblr. Fully distributed.' },
      { name: 'Zapier', note: 'Fully remote.' },
      { name: 'Shopify', note: '“Digital by default.”' },
      { name: 'Dropbox', note: '“Virtual First.”' },
      { name: 'Coinbase', note: 'Remote-first.' },
      { name: 'Buffer', note: 'Fully remote, public salaries.' },
    ],
  },
];

// Lists ranked by how many of their tags appear in the person's titles and strengths.
// Short tags ("ai", "pr") must match whole words; longer ones match word starts ("distribut…").
function tagMatcher(tag) {
  const esc = tag.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(tag.length <= 3 ? `\\b${esc}\\b` : `\\b${esc}`, 'i');
}

export function rankPacks(profile) {
  const text = [...(profile.titles || []), ...(profile.keywords || []), profile.relocation === 'never' ? 'remote' : ''].join(' ');
  return COMPANY_PACKS.map((pack) => ({
    pack,
    score: pack.tags.filter((t) => tagMatcher(t).test(text)).length,
  }))
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((x) => x.pack);
}

export function packAdded(pack, companies) {
  const have = new Set(companies.map((c) => c.name));
  return pack.companies.every((c) => have.has(c.name));
}
